[build]
functions = "functions-build"
# This will be run the site build
command = "yarn build"
# This is the directory is publishing to netlify's CDN
publish = "out"

[template.environment]
FAUNADB_SERVER_SECRET = "Your FaunaDB Server Secret"

[[headers]]
for = "/*"
[headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "form-action https:"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    Feature-Policy = "vibrate 'none'; geolocation 'none'; midi 'none'; notifications 'none'; push 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; fullscreen 'none'; payment 'none'"